### PR TITLE
add log cb (doc)

### PR DESCRIPTION
**Pull request by nick-zh**
https://github.com/arnaud-lb/php-rdkafka/pull/253

### CODE REVIEW

**Comment by kirachen1991** [comment]
so this feature can be use in version 4.0.0 ? why not version 3.1.3……it will be wait for so a long time……TAT

**Comment by nick-zh** [comment]
@kirachen1991 due to some of the PRs that are in master (or will be in master soon), the next version will actually be `4.0.0`, there are about still 5 PRs that need merging, then we'll have `4.0.0` :tada:

**Comment by nick-zh** [comment]
i forgot to mention, since the code is already in master, you could of course clone and build master to use it.

**Comment by kirachen1991** [comment]
oh, i see, thank you so much~~~

**Comment by arnaud-lb** [comment]
Thanks !

**Pull request merged**
