### PR TITLE
add queryWatermarkOffsets for high level (doc)

### PR DESCRIPTION
**Pull request by nick-zh**
https://github.com/arnaud-lb/php-rdkafka/pull/271

### CODE REVIEW

**Comment by arnaud-lb** [comment]
Could you resolve the conflicts ? Then I will merge :)

**Comment by nick-zh** [comment]
done :)

**Comment by nick-zh** [comment]
Since this is in master it would be nice to merge this @arnaud-lb

**Comment by arnaud-lb** [comment]
Thanks !

**Pull request merged**
